import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {DeleteSurveyDialog} from '@/components/delete-survey-dialog';
import {DuplicateSurveyDialog} from '@/components/duplicate-survey-dialog';
import {LoadingOverlay} from '@/components/loading-overlay';
import {Toaster} from '@/components/ui/sonner';
import {QueryClientProvider} from '@/lib/query-client/provider';
import {cn} from '@/utils/classnames';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn('bg-background font-sans antialiased', inter.variable)}
      >
        <QueryClientProvider>
          <LoadingOverlay>
            <DuplicateSurveyDialog>
              <DeleteSurveyDialog>{children}</DeleteSurveyDialog>
            </DuplicateSurveyDialog>
          </LoadingOverlay>
        </QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
