import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {SessionProvider} from '@/auth/_components/session-provider';
import {DeleteSurveyDialog} from '@/components/delete-survey-dialog';
import {DuplicateSurveyDialog} from '@/components/duplicate-survey-dialog';
import {LoadingOverlay} from '@/components/loading-overlay';
import {Toaster} from '@/components/ui/sonner';
import {getUser} from '@/lib/auth';
import {QueryClientProvider} from '@/lib/query-client/provider';
import {cn} from '@/lib/utils';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {user} = await getUser();

  return (
    <SessionProvider value={{user}}>
      <QueryClientProvider>
        <LoadingOverlay>
          <DuplicateSurveyDialog>
            <DeleteSurveyDialog>
              <html lang="en">
                <body
                  className={cn(
                    'bg-background font-sans antialiased',
                    inter.variable,
                  )}
                >
                  {children}
                </body>
              </html>
            </DeleteSurveyDialog>
          </DuplicateSurveyDialog>
        </LoadingOverlay>
      </QueryClientProvider>
      <Toaster />
    </SessionProvider>
  );
}
